# Use an OpenJDK base image
FROM openjdk:22-jdk

# Set the working directory in the container
WORKDIR /app

# Copy the Java source files into the container
COPY . .

# Compile the Java files
RUN javac -Xlint:deprecation dstpsend/*.java MulticastSender.java

# Set the entrypoint to run the MulticastSender program
ENTRYPOINT ["java", "-Djava.net.preferIPv4Stack=true", "MulticastSender"]

# Command arguments (multicast address, port, and interval) can be passed when running the container
# Example: docker run <image> 224.0.0.3 4446 2