# Use an OpenJDK base image with Java installed
FROM openjdk:22-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Compile hjStreamServer and the DSTP package
RUN javac -cp . hjStreamServer.java DSTP/dstpsend/*.java

# Set the entrypoint to run hjStreamServer with any provided arguments
ENTRYPOINT ["java", "-cp", ".", "hjStreamServer"]